spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

Geocode:
  apiKey: DkHVGUkIPl-DuPMo_vgiOVP9kze6bIj5snAbAko2V8w