spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8081

#setup logging level
logging:
  level:
    root: INFO
    pl.rstepniewski.libraryapp.log: DEBUG
  # Log file configuration
  file:
    name: logs/libraryapp_log.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"